version: "3.8"

services:
  app:
    image: laravel-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "5000:9000"
    networks:
      - shared_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
